package com.igeek.mvc.domain;

import java.util.Date;
import javax.persistence.*;

import org.springframework.stereotype.Repository;
@Repository
@Table(name = "`orders`")
public class Orders  implements Cloneable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.oid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ordertime
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.total
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    private Double total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.state
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.address
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.name
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.telephone
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.uid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    private String uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.oid
     *
     * @return the value of orders.oid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.oid
     *
     * @param oid the value for orders.oid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public void setOid(String oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ordertime
     *
     * @return the value of orders.ordertime
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ordertime
     *
     * @param ordertime the value for orders.ordertime
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.total
     *
     * @return the value of orders.total
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.total
     *
     * @param total the value for orders.total
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.state
     *
     * @return the value of orders.state
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.state
     *
     * @param state the value for orders.state
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.address
     *
     * @return the value of orders.address
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.address
     *
     * @param address the value for orders.address
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.name
     *
     * @return the value of orders.name
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.name
     *
     * @param name the value for orders.name
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.telephone
     *
     * @return the value of orders.telephone
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.telephone
     *
     * @param telephone the value for orders.telephone
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.uid
     *
     * @return the value of orders.uid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.uid
     *
     * @param uid the value for orders.uid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid;
    }
}