package com.igeek.mvc.domain;

import java.time.chrono.IsoEra;
import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;
import org.springframework.stereotype.Repository;
@Repository
@Table(name="`product`")
public class Product {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product.pid
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    @Id
    private String pid;

    /**
     * @Title: hashCode
     * @Description: TODO(这里用一句话描述这个方法的作用)
     * @return
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((cid == null) ? 0 : cid.hashCode());
        result = prime * result + ((isHot == null) ? 0 : isHot.hashCode());
        result = prime * result + ((marketPrice == null) ? 0 : marketPrice.hashCode());
        result = prime * result + ((pdate == null) ? 0 : pdate.hashCode());
        result = prime * result + ((pdesc == null) ? 0 : pdesc.hashCode());
        result = prime * result + ((pflag == null) ? 0 : pflag.hashCode());
        result = prime * result + ((pid == null) ? 0 : pid.hashCode());
        result = prime * result + ((pimage == null) ? 0 : pimage.hashCode());
        result = prime * result + ((pname == null) ? 0 : pname.hashCode());
        result = prime * result + ((shopPrice == null) ? 0 : shopPrice.hashCode());
        return result;
    }

    /**
     * @Title: equals
     * @Description: TODO(这里用一句话描述这个方法的作用)
     * @param obj
     * @return
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Product other = (Product) obj;

        if (pid == null) {
            if (other.pid != null)
                return false;
        } else if (!pid.equals(other.pid))
            return false;

        return true;
    }

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product.pname
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product.market_price
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    private Double marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product.shop_price
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    private Double shopPrice;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product.pimage
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    private String pimage;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product.pdate
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    @DateTimeFormat(iso=ISO.DATE)
    private Date pdate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product.is_hot
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    private Integer isHot;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product.pdesc
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    private String pdesc;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product.pflag
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    private Integer pflag;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product.cid
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    
    private String cid;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product.pid
     *
     * @return the value of product.pid
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product.pid
     *
     * @param pid
     *            the value for product.pid
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product.pname
     *
     * @return the value of product.pname
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product.pname
     *
     * @param pname
     *            the value for product.pname
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product.market_price
     *
     * @return the value of product.market_price
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public Double getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product.market_price
     *
     * @param marketPrice
     *            the value for product.market_price
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public void setMarketPrice(Double marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product.shop_price
     *
     * @return the value of product.shop_price
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public Double getShopPrice() {
        return shopPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product.shop_price
     *
     * @param shopPrice
     *            the value for product.shop_price
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public void setShopPrice(Double shopPrice) {
        this.shopPrice = shopPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product.pimage
     *
     * @return the value of product.pimage
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public String getPimage() {
        return pimage;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product.pimage
     *
     * @param pimage
     *            the value for product.pimage
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public void setPimage(String pimage) {
        this.pimage = pimage;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product.pdate
     *
     * @return the value of product.pdate
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public Date getPdate() {
        return pdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product.pdate
     *
     * @param pdate
     *            the value for product.pdate
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public void setPdate(Date pdate) {
        this.pdate = pdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product.is_hot
     *
     * @return the value of product.is_hot
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public Integer getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product.is_hot
     *
     * @param isHot
     *            the value for product.is_hot
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public void setIsHot(Integer isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product.pdesc
     *
     * @return the value of product.pdesc
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public String getPdesc() {
        return pdesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product.pdesc
     *
     * @param pdesc
     *            the value for product.pdesc
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public void setPdesc(String pdesc) {
        this.pdesc = pdesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product.pflag
     *
     * @return the value of product.pflag
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public Integer getPflag() {
        return pflag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product.pflag
     *
     * @param pflag
     *            the value for product.pflag
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public void setPflag(Integer pflag) {
        this.pflag = pflag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product.cid
     *
     * @return the value of product.cid
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product.cid
     *
     * @param cid
     *            the value for product.cid
     *
     * @mbg.generated Thu Jul 26 07:23:07 CST 2018
     */
    public void setCid(String cid) {
        this.cid = cid;
    }
}