package com.igeek.domain;

import javax.persistence.*;

@Table(name = "`orderitem`")
public class Orderitem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.itemid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    private String itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.count
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.subtotal
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    private Double subtotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.pid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.oid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    private String oid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.itemid
     *
     * @return the value of orderitem.itemid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.itemid
     *
     * @param itemid the value for orderitem.itemid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public void setItemid(String itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.count
     *
     * @return the value of orderitem.count
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.count
     *
     * @param count the value for orderitem.count
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.subtotal
     *
     * @return the value of orderitem.subtotal
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public Double getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.subtotal
     *
     * @param subtotal the value for orderitem.subtotal
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.pid
     *
     * @return the value of orderitem.pid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.pid
     *
     * @param pid the value for orderitem.pid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.oid
     *
     * @return the value of orderitem.oid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.oid
     *
     * @param oid the value for orderitem.oid
     *
     * @mbg.generated Thu Jul 26 21:42:16 CST 2018
     */
    public void setOid(String oid) {
        this.oid = oid;
    }
}